### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by DerJacques** [RBech/economic-api#1]
Hi there

This looks great! Looking through the source code, I'm not sure if the package can handle e-conomic's pagination? Is this something you have looked into!

Thanks!

**Comment by RBech** [comment]
@DerJacques I haven't looked into that yet no but looking at the documentation all you need is skippages and/or pagesize so you should be able to do 

$customers = $economic->get('customers', [
    'pagesize' => 200,
    'skippages' => 2
]);

It would be nice to do something more fluent in the future but since I will mainly be using this for post requests it's beyond the scope of what I want to do currently, feel free to send a pull request though if you do it

**Comment by DerJacques** [comment]
Thanks for the prompt reply!

Definitely understand why this may not be a top priority. The simple solution you propose definitely works for now.

I'll make sure to send a pull request in case I end up writing a more fluid solution.

Closing this issue for now.
